### ISSUE TITLE
Reflection allows unsafe calls

### ISSUE THREAD

**Issue by jburse** [leaningtech/cheerpj-appletrunner#26]
This might be related to another issue https://github.com/leaningtech/cheerpj-appletrunner/issues/23 under the hood. But I cannot really tell, since I don't know the implementation details.

But it seems to me that Cheerpj allows unsafe calls, where the actual parameters of a method or constructor call do not match the formal parameters.

I have a test case where I exactly do this, the expected behaviour is:

![unbenannt](https://user-images.githubusercontent.com/5411487/50387514-97d09580-06fe-11e9-952d-1b609acaa7b1.PNG)

On the other hand CheerpJ gives me:

![unbenannt2](https://user-images.githubusercontent.com/5411487/50387535-fbf35980-06fe-11e9-88fe-2734452a0ac1.PNG)

**Comment by jburse** [comment]
The method sysGetByte() does the following:

    public static int sysGetByte(InputStream para)
            throws IOException {
        return para.read();
    }

I guess it works by accident, since current_output gives me a Reader. And both InputStream and Reader have a read() method. But such a Duck typing call or whatever, is not valid in Java, also not through reflection. The relevant exception that should be thrown by the reflection invoke method is:

**Comment by jburse** [comment]
As I understand, dropping this check from reflection, could speed up reflection a little. But since I rely on this check, I have to code the check now in Java somehow as a work around.

**Comment by alexp-sssup** [comment]
Fixed in CheerpJ Applet Runner 6.9

**Comment by jburse** [comment]
I did some regression testing. Does not yet work:

Ordinary Java:
```
obj=matula.util.system.ConnectionReader@49eee8b4
java.lang.IllegalArgumentException: object is not an instance of declaring class
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
```
CheerpJ:

```
cheerpOS.js:1407 obj=matula.util.system.ConnectionReader@1891
cheerpOS.js:1407 java.lang.NullPointerException
cheerpOS.js:1407  	at java.io.Reader.read(Unknown Source)
cheerpOS.js:1407  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Unknown Source)
cheerpOS.js:1407  	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
cheerpOS.js:1407  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
cheerpOS.js:1407  	at java.lang.reflect.Method.invoke(Unknown Source)
```
If you look closely the call gets into the target method. Maybe this is
the CheerpJ strategy, maybe not. Somehow I take it, that the call is
still unsafe. At least the thrown error is not according to the Java spec, 

see also other defect here:

**Comment by alexp-sssup** [comment]
You need to provide a test case here too.

**Comment by jburse** [comment]
Here is a test case for this issue:

1. Test Program:

```
public class Test {

    public static void test(InputStream in) {
        System.err.println("reached");
    }

    public static void main(String args) {
        try {
            Reader reader = new StringReader("abc");
            Method method = Test.class.getDeclaredMethod("test", InputStream.class);
            method.invoke(null, reader);
        } catch (Exception x) {
            x.printStackTrace();
        }
    }

}
```
2. Expected Result, from Ordinary Java:

java.lang.IllegalArgumentException: argument type mismatch
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at Test.test(Test.java:52)
