### ISSUE TITLE
Extension does not work on https://www.ocf.berkeley.edu/~jfly/projects/qqTimer/qqTimer.htm

### ISSUE THREAD

**Issue by jfly** [leaningtech/cheerpj-appletrunner#3]
I've installed [this chrome extension](https://chrome.google.com/webstore/detail/cheerpj-applet-runner-bet/bbmolahhldcbngedljfadjlognfaaein).

When visiting this page: https://www.ocf.berkeley.edu/~jfly/projects/qqTimer/qqTimer.htm and telling the extension to run the applet on that page, all I see it a gray box:

![2017-07-07_07 09 58_867x910_kaladin](https://user-images.githubusercontent.com/277474/27961476-a020491c-62e3-11e7-9e3b-2cea959b2540.png)

There are a number of errors in the javascript console, including an assertion failure that might be useful:

<details>

```
Applet init
loader.js:2737 CheerpJ is initializing
loader.js:2737 CheerpJ runtime ready
cheerpjdeploy.leaningtech.com/cheerpj/lib/accessibility.properties Failed to load resource: the server responded with a status of 404 ()
sun/applet/resources/MsgAppletViewer_en.class Failed to load resource: the server responded with a status of 404 (Not Found)
sun/applet/resources/MsgAppletViewer_en.properties Failed to load resource: the server responded with a status of 404 (Not Found)
2com/leaningtech/handlers/https/Handler.class Failed to load resource: the server responded with a status of 404 (Not Found)
2sun/security/ec/SunEC.class Failed to load resource: the server responded with a status of 404 (Not Found)
com/sun/crypto/provider/SunJCE.class Failed to load resource: the server responded with a status of 404 (Not Found)
cheerpjdeploy.leaningtech.com/cheerpj/lib/security/jssecacerts Failed to load resource: the server responded with a status of 404 ()
2sun/security/ec/SunEC.class Failed to load resource: the server responded with a status of 404 (Not Found)
2cheerpjdeploy.leaningtech.com/cheerpj/lib/net.properties Failed to load resource: the server responded with a status of 404 ()
GamesCubeMan.jar.js Failed to load resource: the server responded with a status of 404 (Not Found)
2cheerpj.js:1 SUPPORT CONSTANT FIELD 6
cheerpjdeploy.leaningtech.com/cheerpj/lib/swing.properties Failed to load resource: the server responded with a status of 404 ()
cheerpjdeploy.leaningtech.com/cheerpj/lib/ext/localedata.jar Failed to load resource: the server responded with a status of 404 ()
cheerpjdeploy.leaningtech.com/cheerpj/lib/currency.properties Failed to load resource: the server responded with a status of 404 ()
cheerpjdeploy.leaningtech.com/cheerpj/lib/fonts/LucidaSansRegular.ttf Failed to load resource: the server responded with a status of 404 ()
cheerpjdeploy.leaningtech.com/cheerpj/lib/fonts/badfonts.txt Failed to load resource: the server responded with a status of 404 ()
cheerpjdeploy.leaningtech.com/cheerpj/lib/fonts/fallback Failed to load resource: the server responded with a status of 404 ()
loader.js:801 java.lang.reflect.InvocationTargetException
loader.js:801 

cheerpj.js:1 assertion "false" failed: file "CheerpJCompression.cpp", line 327, function: static uint8_t CheerpJCompiler::CompressedState::getIdentifierBase64Value(char)
loader.js:801 	at java.lang.Throwable.getOurStackTrace(Unknown Source)
loader.js:801 

loader.js:801 	at java.lang.Throwable.getOurStackTrace(Unknown Source)
loader.js:801 

loader.js:801 	at java.lang.Throwable.printStackTrace(Unknown Source)
loader.js:801 

loader.js:801 	at java.lang.Throwable.printStackTrace(Unknown Source)
loader.js:801 

loader.js:801 	at java.lang.Throwable.printStackTrace(Unknown Source)
loader.js:801 

loader.js:801 	at edu.berkeley.gcweb.gui.gamescubeman.PuzzleUtils.GamesCubeMan.init(Unknown Source)
loader.js:801 

loader.js:801 	at sun.applet.AppletPanel.run(Unknown Source)
loader.js:801 

loader.js:801 Caused by: java.lang.ClassCastException
loader.js:801 
```

</details>

**Comment by alexp-sssup** [comment]
I have fixed the issue that blocks the loading. I will close this bug when a new build is publicly available.

**Comment by alexp-sssup** [comment]
Fixed long time ago. Closing.
