### ISSUE TITLE
got error then applet stop

### ISSUE THREAD

**Issue by umjammer** [leaningtech/cheerpj-appletrunner#41]
### source

 * Java2D.jar (this is sun's official demo demo/jfc/Java2D. it's long time ago i got this, so i can't point the location of this source)

### env

 * macOS 10.15.4
 * Chrome Version: 85.0.4173.2（Official Build）dev （64 Bit）

### chrome log
```
cjrtnc.leaningtech.com/20200206/loader.js:404 Uncaught RuntimeError: function signature mismatch
    at <anonymous>:wasm-function[583]:0x366fc
    at jnF$ (<anonymous>:wasm-function[2122]:0xc4330)
    at _Java_com_sun_imageio_plugins_jpeg_JPEGImageWriter_initJPEGImageWriter (https://cjrtnc.leaningtech.com/20200206/jni.js:1:1549373)
    at _c4pcQZ9ocdGbbIZ$ZcLbsJeEYdHrD$yQhOirzWmCeYeruDpsdY0tumShoo (https://cjrtnc.leaningtech.com/20200206/runtime/rt.jar.com.sun.imageio.plugins.jpeg.js:150:1237)
    at _c4pcQZ9ocdGbbIZ$ZcLbsJeEYdHrD$yQhOirzOmCeYereNThn (https://cjrtnc.leaningtech.com/20200206/runtime/rt.jar.com.sun.imageio.plugins.jpeg.js:161:1227)
    at Object.eval [as func] (eval at buildContinuations (https://cjrtnc.leaningtech.com/20200206/loader.js:118:23), <anonymous>:3:182)
    at runContinuationStack (https://cjrtnc.leaningtech.com/20200206/loader.js:390:10)
    at cheerpjSchedule (https://cjrtnc.leaningtech.com/20200206/loader.js:1108:5)
    at IFrameProxyDownloader.dl.onload (https://cjrtnc.leaningtech.com/20200206/cheerpOS.js:382:6)
    at MessagePort.ipfMessage (https://cjrtnc.leaningtech.com/20200206/loader.js:3537:6)
```

**Comment by alexp-sssup** [comment]
Can you share the binary Java2D.jar with us and the HTML page you use for integration? It would be great if you could simply publish this somewhere so that we can test directly with Applet Runner

**Comment by umjammer** [comment]
here it is.

[Java2Demo.jar.zip](https://github.com/leaningtech/cheerpj-appletrunner/files/4827502/Java2Demo.jar.zip)

**Comment by umjammer** [comment]
[Java2Demo.html.zip](https://github.com/leaningtech/cheerpj-appletrunner/files/4829962/Java2Demo.html.zip)

put `Java2Demo.html` and `Java2Demo.jar` into the same directory.
and run `python -m http.server 8000` at the directory.
then browse `http://localhost:8000/Java2Demo.html`

**Comment by alexp-sssup** [comment]
We can reproduce a problem in the "Images" tab of the demo. We have written this down in our internal bug tracked and we will let you know when the problem is fixed.

Unfortunately Google is keeping our CheerpJ Applet Runner extension under review (without any explanation) since months and we are not able to fix any issue at this point.

CheerpJ Applet Runner is just a demo of our technology. If you need CheerpJ in a commercial setting please get in touch with sales@leaningtech.com

**Comment by marsicplusplus** [comment]
Hi @umjammer 

We have added the missing functions that caused the issues on your example.
You can find the updated runtime at https://cjrtnc.leaningtech.com/20210802/loader.js

Thanks for reporting this to us.

Best, 
Lorenzo
